apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snapshotcontrollers.snapshotoperator.openshift.io
spec:
  group: snapshotoperator.openshift.io
  names:
    kind: SnapshotController
    listKind: SnapshotControllerList
    plural: snapshotcontrollers
    singular: snapshotcontroller
  scope: Namespaced
  version: v1alpha1
