kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: snapshot-operator
rules:
- apiGroups:
  - snapshotoperator.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - persistentvolumes
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["create", "list", "watch", "delete"]
- apiGroups:
  - volumesnapshot.external-storage.k8s.io
  resources:
  - volumesnapshots
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - volumesnapshot.external-storage.k8s.io
  resources:
  - volumesnapshotdatas
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-snapshot-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: snapshot
roleRef:
  kind: ClusterRole
  name: snapshot-operator
  apiGroup: rbac.authorization.k8s.io
