---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: snapshot-operator
  labels:
    app: snapshot-operator
spec:
  lookupPolicy:
    local: false
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: snapshot-operator
  labels:
    app: snapshot-operator
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    git:
      uri: https://github.com/Ananasr/snapshot-operator
      ref: master
    type: Dockerfile
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: snapshot-operator:latest
