apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: snapshot-operator
  template:
    metadata:
      labels:
        name: snapshot-operator
    spec:
      containers:
        - name: snapshot-operator
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - snapshot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "snapshot-operator"
