apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: snapshot-operator
  labels:
    app: snapshot-operator
spec:
  replicas: 1
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - snapshot-operator
        from:
          kind: ImageStreamTag
          name: snapshot-operator:latest
      type: ImageChange
    - type: ConfigChange
  template:
    metadata:
      labels:
        app: snapshot-operator
    spec:
      containers:
        - name: snapshot-operator
          image: snapshot-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "snapshot-operator"
